In [19]:
import random as r
import numpy as np     

final_state = np.array([[1,2,3],[4,5,6],[7,8,0]])
temp = list(final_state.flatten())


In [32]:
initial_state = '012375684'
initial_state = list(initial_state)
initial_state = np.reshape(initial_state,(3,3)).astype(int)
print(initial_state)

[[0 1 2]
 [3 7 5]
 [6 8 4]]


In [21]:
#tìm đường đi

def find_path(state):
    #tìm vị trí của số 0
    row = np.squeeze(np.where(state == 0)[0]) 
    col = np.squeeze(np.where(state == 0)[1])
    # up
    if (row - 1) >= 0:
        temp = state.copy()
        temp[row,col], temp[row-1,col] = temp[row-1,col], temp[row,col] #đổi vị trí
        yield temp
    #down
    if (row + 1) < len(state):
        temp = state.copy()
        temp[row,col], temp[row+1,col] = temp[row+1,col], temp[row,col] #đổi vị trí
        yield temp
    #right
    if (col + 1) < len(state):
        temp = state.copy()
        temp[row,col], temp[row,col+1] = temp[row,col+1], temp[row,col] #đổi vị trí
        yield temp
    #left
    if (col - 1) >= 0:
        temp = state.copy()
        temp[row,col], temp[row,col-1] = temp[row,col-1], temp[row,col] #đổi vị trí
        yield temp

In [22]:
#tính h-score
def h(state, goal):
    score = 0
    for i in range(len(state)):
        for j in range(len(state[i])):
            if state[i,j] != goal[i,j] and state[i,j] != 0:
                score += 1
    return score

In [34]:
import time

start = time.time()
closed_queue = []

g_score = 1
state = initial_state.copy()
temp_queue = list(find_path(state))
f_score_first_state = [g_score + h(state, final_state) for state in temp_queue]

priority_queue = list(zip(temp_queue, f_score_first_state))
priority_queue = sorted(priority_queue, key=lambda x: x[1])

priority_queue = [[[state[0]],state[1]] for state in priority_queue]


## A* Search

while priority_queue != []:

    p = priority_queue.pop(0)
    x = p[0][-1]
    g_score = len(p[0])
    if (g_score > 100):
        print('Không thể giải được') # Break point
        break
    if x.tolist() in closed_queue:
        continue
    if np.array_equal(x, final_state):
        print('Level:  0')
        print(initial_state)
        for idx in range(len(p[0])):
            print('*'*20)
            print('Level: ',idx+1)
            print(p[0][idx])
        break
    closed_queue.append(x.tolist())
    for y in find_path(x):
        subtemp = p[0].copy()
        f_score = g_score + 1 + h(y, final_state)
        subtemp.append(y)
        temp = [subtemp, f_score]
        priority_queue.append(temp)
    priority_queue = sorted(priority_queue, key=lambda x: x[1])
    
end = time.time()

print('Run time: ', end-start,'s')
    


Level:  0
[[0 1 2]
 [3 7 5]
 [6 8 4]]
********************
Level:  1
[[1 0 2]
 [3 7 5]
 [6 8 4]]
********************
Level:  2
[[1 7 2]
 [3 0 5]
 [6 8 4]]
********************
Level:  3
[[1 7 2]
 [0 3 5]
 [6 8 4]]
********************
Level:  4
[[1 7 2]
 [6 3 5]
 [0 8 4]]
********************
Level:  5
[[1 7 2]
 [6 3 5]
 [8 0 4]]
********************
Level:  6
[[1 7 2]
 [6 3 5]
 [8 4 0]]
********************
Level:  7
[[1 7 2]
 [6 3 0]
 [8 4 5]]
********************
Level:  8
[[1 7 2]
 [6 0 3]
 [8 4 5]]
********************
Level:  9
[[1 7 2]
 [0 6 3]
 [8 4 5]]
********************
Level:  10
[[1 7 2]
 [8 6 3]
 [0 4 5]]
********************
Level:  11
[[1 7 2]
 [8 6 3]
 [4 0 5]]
********************
Level:  12
[[1 7 2]
 [8 0 3]
 [4 6 5]]
********************
Level:  13
[[1 0 2]
 [8 7 3]
 [4 6 5]]
********************
Level:  14
[[1 2 0]
 [8 7 3]
 [4 6 5]]
********************
Level:  15
[[1 2 3]
 [8 7 0]
 [4 6 5]]
********************
Level:  16
[[1 2 3]
 [8 7 5]
 [4 6 0]]
***********