In [3]:
import random as r
import numpy as np     

final_state = np.array([[1,2,3,4],[12,13,14,5],[11,0,15,6],[10,9,8,7]])
temp = list(final_state.flatten())


In [5]:
initial_state = '11 14 4 7 10 6 0 5 1 2 13 15 9 12 8 3'
initial_state = np.fromstring(initial_state, dtype=int, sep=' ')
initial_state = np.reshape(initial_state, (4,4)).astype(int)
print(initial_state)

[[11 14  4  7]
 [10  6  0  5]
 [ 1  2 13 15]
 [ 9 12  8  3]]


In [6]:
#tìm đường đi

def find_path(state):
    #tìm vị trí của số 0
    row = np.squeeze(np.where(state == 0)[0]) 
    col = np.squeeze(np.where(state == 0)[1])
    # up
    if (row - 1) >= 0:
        temp = state.copy()
        temp[row,col], temp[row-1,col] = temp[row-1,col], temp[row,col] #đổi vị trí
        yield temp
    #down
    if (row + 1) < len(state):
        temp = state.copy()
        temp[row,col], temp[row+1,col] = temp[row+1,col], temp[row,col] #đổi vị trí
        yield temp
    #right
    if (col + 1) < len(state):
        temp = state.copy()
        temp[row,col], temp[row,col+1] = temp[row,col+1], temp[row,col] #đổi vị trí
        yield temp
    #left
    if (col - 1) >= 0:
        temp = state.copy()
        temp[row,col], temp[row,col-1] = temp[row,col-1], temp[row,col] #đổi vị trí
        yield temp

In [7]:
#tính h-score
def h(state, goal):
    score = 0
    for i in range(len(state)):
        for j in range(len(state[i])):
            if state[i,j] != goal[i,j] and state[i,j] != 0:
                score += 1
    return score

In [8]:
import time 

start = time.time()
closed_queue = []

g_score = 1
state = initial_state.copy()
temp_queue = list(find_path(state))
f_score_first_state = [g_score + h(state, final_state) for state in temp_queue]

priority_queue = list(zip(temp_queue, f_score_first_state))
priority_queue = sorted(priority_queue, key=lambda x: x[1])

priority_queue = [[[state[0]],state[1]] for state in priority_queue]

while priority_queue != []:

    p = priority_queue.pop(0)
    x = p[0][-1]
    g_score = len(p[0])
    if (g_score > 100):
        print('Không thể giải được') #Break point
        break
    if x.tolist() in closed_queue:
        continue
    if np.array_equal(x, final_state):
        print('Level: 0')
        print(initial_state)
        for idx in range(len(p[0])):
            print('*'*20)
            print('Level: ',idx+1)
            print(p[0][idx])
        break
    closed_queue.append(x.tolist())
    for y in find_path(x):
        subtemp = p[0].copy()
        f_score = g_score + 1 + h(y, final_state)
        subtemp.append(y)
        temp = [subtemp, f_score]
        priority_queue.append(temp)
    priority_queue = sorted(priority_queue, key=lambda x: x[1])
    
end = time.time()

print('Run time: ', end-start, 's')



KeyboardInterrupt: 