In [125]:
import random as r
import numpy as np     

final_state = np.array([[1,2,3],[4,5,6],[7,8,0]])
temp = list(final_state.flatten())


In [127]:
initial_state = np.array([[1, 8, 2], [0, 4, 3], [7, 6, 5]])
print(initial_state)

[[1 8 2]
 [0 4 3]
 [7 6 5]]


In [128]:
#tìm đường đi

def find_path(state):
    #tìm vị trí của số 0
    row = np.squeeze(np.where(state == 0)[0]) 
    col = np.squeeze(np.where(state == 0)[1])
    # up
    if (row - 1) >= 0:
        temp = state.copy()
        temp[row,col], temp[row-1,col] = temp[row-1,col], temp[row,col] #đổi vị trí
        yield temp
    #down
    if (row + 1) < len(state):
        temp = state.copy()
        temp[row,col], temp[row+1,col] = temp[row+1,col], temp[row,col] #đổi vị trí
        yield temp
    #right
    if (col + 1) < len(state):
        temp = state.copy()
        temp[row,col], temp[row,col+1] = temp[row,col+1], temp[row,col] #đổi vị trí
        yield temp
    #left
    if (col - 1) >= 0:
        temp = state.copy()
        temp[row,col], temp[row,col-1] = temp[row,col-1], temp[row,col] #đổi vị trí
        yield temp

In [129]:
#tính h-score
def h(state, goal):
    score = 0
    for i in range(len(state)):
        for j in range(len(state[i])):
            if state[i,j] != goal[i,j] and state[i,j] != 0:
                score += 1
    return score

In [130]:
closed_queue = []

g_score = 1
state = initial_state.copy()
temp_queue = list(find_path(state))
f_score_first_state = [g_score + h(state, final_state) for state in temp_queue]

priority_queue = list(zip(temp_queue, f_score_first_state))
sorted(priority_queue, key=lambda x: x[1])

priority_queue = [[[state[0]],state[1]] for state in priority_queue]

while priority_queue != []:
    p = priority_queue.pop(0)
    x = p[0][-1]
    g_score = len(p[0])
    if (g_score > 15):
      print('Không thể giải được')
      break
    if x.tolist() in closed_queue:
        continue
    if np.array_equal(x, final_state):
        print('Level: 0')
        print(initial_state)
        for idx in range(len(p[0])):
            print('*'*20)
            print('Level: ',idx+1)
            print(p[0][idx])
        break
    closed_queue.append(x.tolist())
    for y in find_path(x):
        subtemp = p[0].copy()
        f_score = g_score + 1 + h(y, final_state)
        subtemp.append(y)
        temp = [subtemp, f_score]
        priority_queue.append(temp)
    priority_queue = sorted(priority_queue, key=lambda x: x[1])
    
    


Level: 0
[[1 8 2]
 [0 4 3]
 [7 6 5]]
********************
Level:  1
[[1 8 2]
 [4 0 3]
 [7 6 5]]
********************
Level:  2
[[1 0 2]
 [4 8 3]
 [7 6 5]]
********************
Level:  3
[[1 2 0]
 [4 8 3]
 [7 6 5]]
********************
Level:  4
[[1 2 3]
 [4 8 0]
 [7 6 5]]
********************
Level:  5
[[1 2 3]
 [4 8 5]
 [7 6 0]]
********************
Level:  6
[[1 2 3]
 [4 8 5]
 [7 0 6]]
********************
Level:  7
[[1 2 3]
 [4 0 5]
 [7 8 6]]
********************
Level:  8
[[1 2 3]
 [4 5 0]
 [7 8 6]]
********************
Level:  9
[[1 2 3]
 [4 5 6]
 [7 8 0]]
